import asyncio
import json
from dotenv import load_dotenv

load_dotenv()

from app.services.document_pipeline import analyze_with_qwen

resume_text = """
[ID: b0] EDUCATION

[ID: b1] Motivated computer science student...

[ID: b2] PROFILE SUMMARY

[ID: b3] Jakapan Ploensup

[ID: b4] EXPERIENCE

[ID: b5] Freelance Web Developer (2024 – Present)

[ID: b6] Partnered directly with clients...

[ID: b7] SELECTED TECHNICAL PROJECTS

[ID: b8] AI Product Moderation System...

[ID: b9] Developed...

[ID: b10] Game Boss Automation Bot

[ID: b11] ...

[ID: b12] AI Music Recommendation Engine

[ID: b13] ...

[ID: b14] Personal Portfolio Website

[ID: b15] ...

[ID: b16] Faculty : School of Information and Technology Innovation
Computer Science Data Science and Cyber Security
Bangkok University
July 2023 - Present

[ID: b17] Email...
Github...
LikedIn...
MyWebsite...

[ID: b18] Address...
Phone...

[ID: b19] CONTACT

[ID: b20] SKILLS

[ID: b21] Programming Languages...

[ID: b22] English Program
Sawananan Wittaya School

[ID: b23] 2019 - 2023
"""

async def main():
    print("Sending to Qwen...")
    ai_evaluation = await analyze_with_qwen(resume_text, "Jakapan Ploensup", "Software Developer")
    
    # Dump the exact structured JSON generated by Qwen
    print("--- QWEN JSON OUTPUT ---")
    print(ai_evaluation.model_dump_json(indent=2))

if __name__ == "__main__":
    asyncio.run(main())
